#!/usr/bin/env Rscript


source("top_genes.R")
source("fix_dfs.R")

Chem_gen_master_df<- read.delim("Chem_gen_master_df.tsv", header=TRUE, stringsAsFactors=FALSE)
running_sig_gene_list<- list()
#repeat lines for each df

df<-read.delim("22Dipyridyl_results.csv", header=TRUE, stringsAsFactors=FALSE)
df<- fix_dfs(df)
tg<- top_genes(df)
x<- which(Chem_gen_master_df[,1] %in% tg)
running_sig_gene_list<- append(running_sig_gene_list, as.character(Chem_gen_master_df[x, 1]))
df<-read.delim("24Dimethylimidazole_results.csv", header=TRUE, stringsAsFactors=FALSE)
df<- fix_dfs(df)
tg<- top_genes(df)
x<- which(Chem_gen_master_df[,1] %in% tg)
running_sig_gene_list<- append(running_sig_gene_list, as.character(Chem_gen_master_df[x, 1]))
df<-read.delim("26Dimethylpyrazine_results.csv", header=TRUE, stringsAsFactors=FALSE)
df<- fix_dfs(df)
tg<- top_genes(df)
x<- which(Chem_gen_master_df[,1] %in% tg)
running_sig_gene_list<- append(running_sig_gene_list, as.character(Chem_gen_master_df[x, 1]))
df<-read.delim("2Methylimidazole_results.csv", header=TRUE, stringsAsFactors=FALSE)
df<- fix_dfs(df)
tg<- top_genes(df)
x<- which(Chem_gen_master_df[,1] %in% tg)
running_sig_gene_list<- append(running_sig_gene_list, as.character(Chem_gen_master_df[x, 1]))
df<-read.delim("45Methylimidazole_results.csv", header=TRUE, stringsAsFactors=FALSE)
df<- fix_dfs(df)
tg<- top_genes(df)
x<- which(Chem_gen_master_df[,1] %in% tg)
running_sig_gene_list<- append(running_sig_gene_list, as.character(Chem_gen_master_df[x, 1]))
df<-read.delim("4OHAcetophenone_results.csv", header=TRUE, stringsAsFactors=FALSE)
df<- fix_dfs(df)
tg<- top_genes(df)
x<- which(Chem_gen_master_df[,1] %in% tg)
running_sig_gene_list<- append(running_sig_gene_list, as.character(Chem_gen_master_df[x, 1]))
df<-read.delim("4OHBenzaldehyde_results.csv", header=TRUE, stringsAsFactors=FALSE)
df<- fix_dfs(df)
tg<- top_genes(df)
x<- which(Chem_gen_master_df[,1] %in% tg)
running_sig_gene_list<- append(running_sig_gene_list, as.character(Chem_gen_master_df[x, 1]))
df<-read.delim("4OHBenzoicAcid_results.csv", header=TRUE, stringsAsFactors=FALSE)
df<- fix_dfs(df)
tg<- top_genes(df)
x<- which(Chem_gen_master_df[,1] %in% tg)
running_sig_gene_list<- append(running_sig_gene_list, as.character(Chem_gen_master_df[x, 1]))
df<-read.delim("5HMF_results.csv", header=TRUE, stringsAsFactors=FALSE)
df<- fix_dfs(df)
tg<- top_genes(df)
x<- which(Chem_gen_master_df[,1] %in% tg)
running_sig_gene_list<- append(running_sig_gene_list, as.character(Chem_gen_master_df[x, 1]))
df<-read.delim("Acetamide_results.csv", header=TRUE, stringsAsFactors=FALSE)
df<- fix_dfs(df)
tg<- top_genes(df)
x<- which(Chem_gen_master_df[,1] %in% tg)
running_sig_gene_list<- append(running_sig_gene_list, as.character(Chem_gen_master_df[x, 1]))
df<-read.delim("AcetoSyringone_results.csv", header=TRUE, stringsAsFactors=FALSE)
df<- fix_dfs(df)
tg<- top_genes(df)
x<- which(Chem_gen_master_df[,1] %in% tg)
running_sig_gene_list<- append(running_sig_gene_list, as.character(Chem_gen_master_df[x, 1]))
df<-read.delim("Acetovanillone_results.csv", header=TRUE, stringsAsFactors=FALSE)
df<- fix_dfs(df)
tg<- top_genes(df)
x<- which(Chem_gen_master_df[,1] %in% tg)
running_sig_gene_list<- append(running_sig_gene_list, as.character(Chem_gen_master_df[x, 1]))
df<-read.delim("AzelaicAcid_results.csv", header=TRUE, stringsAsFactors=FALSE)
df<- fix_dfs(df)
tg<- top_genes(df)
x<- which(Chem_gen_master_df[,1] %in% tg)
running_sig_gene_list<- append(running_sig_gene_list, as.character(Chem_gen_master_df[x, 1]))
df<-read.delim("BMIMCl_results.csv", header=TRUE, stringsAsFactors=FALSE)
df<- fix_dfs(df)
tg<- top_genes(df)
x<- which(Chem_gen_master_df[,1] %in% tg)
running_sig_gene_list<- append(running_sig_gene_list, as.character(Chem_gen_master_df[x, 1]))
df<-read.delim("Benomyl_results.csv", header=TRUE, stringsAsFactors=FALSE)
df<- fix_dfs(df)
tg<- top_genes(df)
x<- which(Chem_gen_master_df[,1] %in% tg)
running_sig_gene_list<- append(running_sig_gene_list, as.character(Chem_gen_master_df[x, 1]))
df<-read.delim("BenzoicAcid_results.csv", header=TRUE, stringsAsFactors=FALSE)
df<- fix_dfs(df)
tg<- top_genes(df)
x<- which(Chem_gen_master_df[,1] %in% tg)
running_sig_gene_list<- append(running_sig_gene_list, as.character(Chem_gen_master_df[x, 1]))
df<-read.delim("CV_results.csv", header=TRUE, stringsAsFactors=FALSE)
df<- fix_dfs(df)
tg<- top_genes(df)
x<- which(Chem_gen_master_df[,1] %in% tg)
running_sig_gene_list<- append(running_sig_gene_list, as.character(Chem_gen_master_df[x, 1]))
df<-read.delim("CaffeicAcid_results.csv", header=TRUE, stringsAsFactors=FALSE)
df<- fix_dfs(df)
tg<- top_genes(df)
x<- which(Chem_gen_master_df[,1] %in% tg)
running_sig_gene_list<- append(running_sig_gene_list, as.character(Chem_gen_master_df[x, 1]))
df<-read.delim("CinnamicAcid_results.csv", header=TRUE, stringsAsFactors=FALSE)
df<- fix_dfs(df)
tg<- top_genes(df)
x<- which(Chem_gen_master_df[,1] %in% tg)
running_sig_gene_list<- append(running_sig_gene_list, as.character(Chem_gen_master_df[x, 1]))
df<-read.delim("CoumaricAcid_results.csv", header=TRUE, stringsAsFactors=FALSE)
df<- fix_dfs(df)
tg<- top_genes(df)
x<- which(Chem_gen_master_df[,1] %in% tg)
running_sig_gene_list<- append(running_sig_gene_list, as.character(Chem_gen_master_df[x, 1]))
df<-read.delim("CoumaroylAmide_results.csv", header=TRUE, stringsAsFactors=FALSE)
df<- fix_dfs(df)
tg<- top_genes(df)
x<- which(Chem_gen_master_df[,1] %in% tg)
running_sig_gene_list<- append(running_sig_gene_list, as.character(Chem_gen_master_df[x, 1]))
df<-read.delim("DMSO_results.csv", header=TRUE, stringsAsFactors=FALSE)
df<- fix_dfs(df)
tg<- top_genes(df)
x<- which(Chem_gen_master_df[,1] %in% tg)
running_sig_gene_list<- append(running_sig_gene_list, as.character(Chem_gen_master_df[x, 1]))
df<-read.delim("EMIMCl_results.csv", header=TRUE, stringsAsFactors=FALSE)
df<- fix_dfs(df)
tg<- top_genes(df)
x<- which(Chem_gen_master_df[,1] %in% tg)
running_sig_gene_list<- append(running_sig_gene_list, as.character(Chem_gen_master_df[x, 1]))
df<-read.delim("EtOH_results.csv", header=TRUE, stringsAsFactors=FALSE)
df<- fix_dfs(df)
tg<- top_genes(df)
x<- which(Chem_gen_master_df[,1] %in% tg)
running_sig_gene_list<- append(running_sig_gene_list, as.character(Chem_gen_master_df[x, 1]))
df<-read.delim("FerulicAcid_results.csv", header=TRUE, stringsAsFactors=FALSE)
df<- fix_dfs(df)
tg<- top_genes(df)
x<- which(Chem_gen_master_df[,1] %in% tg)
running_sig_gene_list<- append(running_sig_gene_list, as.character(Chem_gen_master_df[x, 1]))
df<-read.delim("FeruloylAmide_results.csv", header=TRUE, stringsAsFactors=FALSE)
df<- fix_dfs(df)
tg<- top_genes(df)
x<- which(Chem_gen_master_df[,1] %in% tg)
running_sig_gene_list<- append(running_sig_gene_list, as.character(Chem_gen_master_df[x, 1]))
df<-read.delim("Furfural_results.csv", header=TRUE, stringsAsFactors=FALSE)
df<- fix_dfs(df)
tg<- top_genes(df)
x<- which(Chem_gen_master_df[,1] %in% tg)
running_sig_gene_list<- append(running_sig_gene_list, as.character(Chem_gen_master_df[x, 1]))
df<-read.delim("GVL_results.csv", header=TRUE, stringsAsFactors=FALSE)
df<- fix_dfs(df)
tg<- top_genes(df)
x<- which(Chem_gen_master_df[,1] %in% tg)
running_sig_gene_list<- append(running_sig_gene_list, as.character(Chem_gen_master_df[x, 1]))
df<-read.delim("Isobutanol_results.csv", header=TRUE, stringsAsFactors=FALSE)
df<- fix_dfs(df)
tg<- top_genes(df)
x<- which(Chem_gen_master_df[,1] %in% tg)
running_sig_gene_list<- append(running_sig_gene_list, as.character(Chem_gen_master_df[x, 1]))
df<-read.delim("LevulinicAcid_results.csv", header=TRUE, stringsAsFactors=FALSE)
df<- fix_dfs(df)
tg<- top_genes(df)
x<- which(Chem_gen_master_df[,1] %in% tg)
running_sig_gene_list<- append(running_sig_gene_list, as.character(Chem_gen_master_df[x, 1]))
df<-read.delim("MBO_results.csv", header=TRUE, stringsAsFactors=FALSE)
df<- fix_dfs(df)
tg<- top_genes(df)
x<- which(Chem_gen_master_df[,1] %in% tg)
running_sig_gene_list<- append(running_sig_gene_list, as.character(Chem_gen_master_df[x, 1]))
df<-read.delim("Methylglyoxal_results.csv", header=TRUE, stringsAsFactors=FALSE)
df<- fix_dfs(df)
tg<- top_genes(df)
x<- which(Chem_gen_master_df[,1] %in% tg)
running_sig_gene_list<- append(running_sig_gene_list, as.character(Chem_gen_master_df[x, 1]))
df<-read.delim("Mycobutanil_results.csv", header=TRUE, stringsAsFactors=FALSE)
df<- fix_dfs(df)
tg<- top_genes(df)
x<- which(Chem_gen_master_df[,1] %in% tg)
running_sig_gene_list<- append(running_sig_gene_list, as.character(Chem_gen_master_df[x, 1]))
df<-read.delim("NAO_results.csv", header=TRUE, stringsAsFactors=FALSE)
df<- fix_dfs(df)
tg<- top_genes(df)
x<- which(Chem_gen_master_df[,1] %in% tg)
running_sig_gene_list<- append(running_sig_gene_list, as.character(Chem_gen_master_df[x, 1]))
df<-read.delim("SinapicAcid_results.csv", header=TRUE, stringsAsFactors=FALSE)
df<- fix_dfs(df)
tg<- top_genes(df)
x<- which(Chem_gen_master_df[,1] %in% tg)
running_sig_gene_list<- append(running_sig_gene_list, as.character(Chem_gen_master_df[x, 1]))
df<-read.delim("SodiumGlyoxylate_results.csv", header=TRUE, stringsAsFactors=FALSE)
df<- fix_dfs(df)
tg<- top_genes(df)
x<- which(Chem_gen_master_df[,1] %in% tg)
running_sig_gene_list<- append(running_sig_gene_list, as.character(Chem_gen_master_df[x, 1]))
df<-read.delim("Syringaldehyde_results.csv", header=TRUE, stringsAsFactors=FALSE)
df<- fix_dfs(df)
tg<- top_genes(df)
x<- which(Chem_gen_master_df[,1] %in% tg)
running_sig_gene_list<- append(running_sig_gene_list, as.character(Chem_gen_master_df[x, 1]))
df<-read.delim("SyringicAcid_results.csv", header=TRUE, stringsAsFactors=FALSE)
df<- fix_dfs(df)
tg<- top_genes(df)
x<- which(Chem_gen_master_df[,1] %in% tg)
running_sig_gene_list<- append(running_sig_gene_list, as.character(Chem_gen_master_df[x, 1]))
df<-read.delim("VanillicAcid_results.csv", header=TRUE, stringsAsFactors=FALSE)
df<- fix_dfs(df)
tg<- top_genes(df)
x<- which(Chem_gen_master_df[,1] %in% tg)
running_sig_gene_list<- append(running_sig_gene_list, as.character(Chem_gen_master_df[x, 1]))
df<-read.delim("Vanillin_results.csv", header=TRUE, stringsAsFactors=FALSE)
df<- fix_dfs(df)
tg<- top_genes(df)
x<- which(Chem_gen_master_df[,1] %in% tg)
running_sig_gene_list<- append(running_sig_gene_list, as.character(Chem_gen_master_df[x, 1]))

running_sig_gene_list<- running_sig_gene_list[!duplicated(running_sig_gene_list)]
enriched_df<- Chem_gen_master_df[which(Chem_gen_master_df[,1] %in% running_sig_gene_list), ]

write.table(enriched_df, "Enriched_chem_gene_master_df.tsv", sep="\t")
