#!/bin/bash

Rscript --vanilla /Users/katiefisher/Sato_lab_chemical_genomics/scripts/BASH_topgenes.r  /Users/katiefisher/Sato_lab_chemical_genomics/raw_data/22Dipyridyl.tsv 22Dipyridyl
Rscript --vanilla /Users/katiefisher/Sato_lab_chemical_genomics/scripts/BASH_topgenes.r  /Users/katiefisher/Sato_lab_chemical_genomics/raw_data/24Dimethylimidazole.tsv 24Dimethylimidazole
Rscript --vanilla /Users/katiefisher/Sato_lab_chemical_genomics/scripts/BASH_topgenes.r  /Users/katiefisher/Sato_lab_chemical_genomics/raw_data/26Dimethylpyrazine.tsv 26Dimethylpyrazine
Rscript --vanilla /Users/katiefisher/Sato_lab_chemical_genomics/scripts/BASH_topgenes.r  /Users/katiefisher/Sato_lab_chemical_genomics/raw_data/2Methylimidazole.tsv 2Methylimidazole
Rscript --vanilla /Users/katiefisher/Sato_lab_chemical_genomics/scripts/BASH_topgenes.r  /Users/katiefisher/Sato_lab_chemical_genomics/raw_data/45Methylimidazole.tsv 45Methylimidazole
Rscript --vanilla /Users/katiefisher/Sato_lab_chemical_genomics/scripts/BASH_topgenes.r  /Users/katiefisher/Sato_lab_chemical_genomics/raw_data/4OHAcetophenone.tsv  4OHAcetophenone
Rscript --vanilla /Users/katiefisher/Sato_lab_chemical_genomics/scripts/BASH_topgenes.r  /Users/katiefisher/Sato_lab_chemical_genomics/raw_data/4OHBenzaldehyde.tsv 4OHBenzaldehyde
Rscript --vanilla /Users/katiefisher/Sato_lab_chemical_genomics/scripts/BASH_topgenes.r  /Users/katiefisher/Sato_lab_chemical_genomics/raw_data/4OHBenzoicAcid.tsv 4OHBenzoicAcid
Rscript --vanilla /Users/katiefisher/Sato_lab_chemical_genomics/scripts/BASH_topgenes.r  /Users/katiefisher/Sato_lab_chemical_genomics/raw_data/5HMF.tsv 5HMF
Rscript --vanilla /Users/katiefisher/Sato_lab_chemical_genomics/scripts/BASH_topgenes.r  /Users/katiefisher/Sato_lab_chemical_genomics/raw_data/Acetamide.tsv Acetamide
Rscript --vanilla /Users/katiefisher/Sato_lab_chemical_genomics/scripts/BASH_topgenes.r  /Users/katiefisher/Sato_lab_chemical_genomics/raw_data/AcetoSyringone.tsv AcetoSyringone
Rscript --vanilla /Users/katiefisher/Sato_lab_chemical_genomics/scripts/BASH_topgenes.r  /Users/katiefisher/Sato_lab_chemical_genomics/raw_data/Acetovanillone.tsv Acetovanillone
Rscript --vanilla /Users/katiefisher/Sato_lab_chemical_genomics/scripts/BASH_topgenes.r  /Users/katiefisher/Sato_lab_chemical_genomics/raw_data/AzelaicAcid.tsv AzelaicAcid
Rscript --vanilla /Users/katiefisher/Sato_lab_chemical_genomics/scripts/BASH_topgenes.r  /Users/katiefisher/Sato_lab_chemical_genomics/raw_data/BMIMCl.tsv BMIMCl
Rscript --vanilla /Users/katiefisher/Sato_lab_chemical_genomics/scripts/BASH_topgenes.r  /Users/katiefisher/Sato_lab_chemical_genomics/raw_data/Benomyl.tsv Benomyl
Rscript --vanilla /Users/katiefisher/Sato_lab_chemical_genomics/scripts/BASH_topgenes.r  /Users/katiefisher/Sato_lab_chemical_genomics/raw_data/BenzoicAcid.tsv BenzoicAcid
Rscript --vanilla /Users/katiefisher/Sato_lab_chemical_genomics/scripts/BASH_topgenes.r  /Users/katiefisher/Sato_lab_chemical_genomics/raw_data/CV.tsv CV
Rscript --vanilla /Users/katiefisher/Sato_lab_chemical_genomics/scripts/BASH_topgenes.r  /Users/katiefisher/Sato_lab_chemical_genomics/raw_data/CaffeicAcid.tsv CaffeicAcid
Rscript --vanilla /Users/katiefisher/Sato_lab_chemical_genomics/scripts/BASH_topgenes.r  /Users/katiefisher/Sato_lab_chemical_genomics/raw_data/CinnamicAcid.tsv CinnamicAcid
Rscript --vanilla /Users/katiefisher/Sato_lab_chemical_genomics/scripts/BASH_topgenes.r  /Users/katiefisher/Sato_lab_chemical_genomics/raw_data/CoumaricAcid.tsv CoumaricAcid
Rscript --vanilla /Users/katiefisher/Sato_lab_chemical_genomics/scripts/BASH_topgenes.r  /Users/katiefisher/Sato_lab_chemical_genomics/raw_data/CoumaroylAmide.tsv CoumaroylAmide
Rscript --vanilla /Users/katiefisher/Sato_lab_chemical_genomics/scripts/BASH_topgenes.r  /Users/katiefisher/Sato_lab_chemical_genomics/raw_data/DMSO.tsv DMSO
Rscript --vanilla /Users/katiefisher/Sato_lab_chemical_genomics/scripts/BASH_topgenes.r  /Users/katiefisher/Sato_lab_chemical_genomics/raw_data/EMIMCl.tsv EMIMCl
Rscript --vanilla /Users/katiefisher/Sato_lab_chemical_genomics/scripts/BASH_topgenes.r  /Users/katiefisher/Sato_lab_chemical_genomics/raw_data/EtOH.tsv EtOH
Rscript --vanilla /Users/katiefisher/Sato_lab_chemical_genomics/scripts/BASH_topgenes.r  /Users/katiefisher/Sato_lab_chemical_genomics/raw_data/FerulicAcid.tsv FerulicAcid
Rscript --vanilla /Users/katiefisher/Sato_lab_chemical_genomics/scripts/BASH_topgenes.r  /Users/katiefisher/Sato_lab_chemical_genomics/raw_data/FeruloylAmide.tsv FeruloylAmide
Rscript --vanilla /Users/katiefisher/Sato_lab_chemical_genomics/scripts/BASH_topgenes.r  /Users/katiefisher/Sato_lab_chemical_genomics/raw_data/Furfural.tsv Furfural
Rscript --vanilla /Users/katiefisher/Sato_lab_chemical_genomics/scripts/BASH_topgenes.r  /Users/katiefisher/Sato_lab_chemical_genomics/raw_data/GVL.tsv GVL
Rscript --vanilla /Users/katiefisher/Sato_lab_chemical_genomics/scripts/BASH_topgenes.r  /Users/katiefisher/Sato_lab_chemical_genomics/raw_data/Isobutanol.tsv Isobutanol
Rscript --vanilla /Users/katiefisher/Sato_lab_chemical_genomics/scripts/BASH_topgenes.r  /Users/katiefisher/Sato_lab_chemical_genomics/raw_data/LevulinicAcid.tsv LevulinicAcid
Rscript --vanilla /Users/katiefisher/Sato_lab_chemical_genomics/scripts/BASH_topgenes.r  /Users/katiefisher/Sato_lab_chemical_genomics/raw_data/MBO.tsv MBO
Rscript --vanilla /Users/katiefisher/Sato_lab_chemical_genomics/scripts/BASH_topgenes.r  /Users/katiefisher/Sato_lab_chemical_genomics/raw_data/Methylglyoxal.tsv Methylglyoxal
Rscript --vanilla /Users/katiefisher/Sato_lab_chemical_genomics/scripts/BASH_topgenes.r  /Users/katiefisher/Sato_lab_chemical_genomics/raw_data/Mycobutanil.tsv Mycobutanil
Rscript --vanilla /Users/katiefisher/Sato_lab_chemical_genomics/scripts/BASH_topgenes.r  /Users/katiefisher/Sato_lab_chemical_genomics/raw_data/NAO.tsv NAO
Rscript --vanilla /Users/katiefisher/Sato_lab_chemical_genomics/scripts/BASH_topgenes.r  /Users/katiefisher/Sato_lab_chemical_genomics/raw_data/SinapicAcid.tsv SinapicAcid
Rscript --vanilla /Users/katiefisher/Sato_lab_chemical_genomics/scripts/BASH_topgenes.r  /Users/katiefisher/Sato_lab_chemical_genomics/raw_data/SodiumGlyoxylate.tsv SodiumGlyoxylate
Rscript --vanilla /Users/katiefisher/Sato_lab_chemical_genomics/scripts/BASH_topgenes.r  /Users/katiefisher/Sato_lab_chemical_genomics/raw_data/Syringaldehyde.tsv Syringaldehyde
Rscript --vanilla /Users/katiefisher/Sato_lab_chemical_genomics/scripts/BASH_topgenes.r  /Users/katiefisher/Sato_lab_chemical_genomics/raw_data/SyringicAcid.tsv SyringicAcid
Rscript --vanilla /Users/katiefisher/Sato_lab_chemical_genomics/scripts/BASH_topgenes.r  /Users/katiefisher/Sato_lab_chemical_genomics/raw_data/VanillicAcid.tsv VanillicAcid
Rscript --vanilla /Users/katiefisher/Sato_lab_chemical_genomics/scripts/BASH_topgenes.r  /Users/katiefisher/Sato_lab_chemical_genomics/raw_data/Vanillin.tsv Vanillin
Rscript --vanilla /Users/katiefisher/Sato_lab_chemical_genomics/scripts/BASH_topgenes.r  /Users/katiefisher/Sato_lab_chemical_genomics/raw_data/SodiumAcetate.tsv SodiumAcetate
Rscript --vanilla /Users/katiefisher/Sato_lab_chemical_genomics/scripts/BASH_topgenes.r  /Users/katiefisher/Sato_lab_chemical_genomics/raw_data/SodiumButyrate.tsv SodiumButyrate
